baseurl = "https://www.lonesomecrowdedweb.com/"
builddrafts = false
canonifyurls = true
contentdir = "content"
author = "Patrick Johannessen"
title = "Lonesome Crowded Web"
languageCode = "en-AU"
layoutdir = "layouts"
publishdir = "public"
pygmentscodefences = true
pygmentsuseclasses = true
disqusshortname     = "lonesomecrowdedweb"
pluralizelisttitles = false
googleAnalytics = "UA-88445668-1"

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Patrick Johannessen"
cachebuster = true    
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Don't panic"
github = "https://github.com/pjohannessen"
instagram = "https://www.instagram.com/pajohannessen/"
lang = "en"
linkedin = "https://www.linkedin.com/in/patrickjohannessen"
stackoverflow = "https://stackoverflow.com/users/129967/patrickj"
title = "The Lonesome Crowded Web"
twitter = "https://twitter.com/pajohannessen"

[social]
twitter = "pajohannessen"