baseurl = "https://www.lonesomecrowdedweb.com/"
builddrafts = false
canonifyurls = true
contentdir = "content"
author = "Patrick Johannessen"
title = "Lonesome Crowded Web"
languageCode = "en-AU"
layoutdir = "layouts"
publishdir = "public"
pygmentsStyle       = "dracula"
pygmentsCodeFences  = true
disqusshortname     = "lonesomecrowdedweb"
pluralizelisttitles = false
googleAnalytics = "UA-88445668-1"

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[[menu.main]]
name                   = "Home"
weight                 = -120
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[params]
author                 = "Patrick Johannessen"
cachebuster            = true
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
github                 = "https://github.com/pjohannessen"
gravatar               = "823bf30ed436754804af7fb9a61a102c"
i18n_flags             = false                         # whether to display small country flags for available translations
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
instagram              = "https://www.instagram.com/pajohannessen/"
lang                   = "en"
latestpostscount       = 10                            # how many posts to display on the home page
linkedin               = "https://www.linkedin.com/in/patrickjohannessen"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
stackoverflow          = "https://stackoverflow.com/users/129967/patrickj"
title                  = "The Lonesome Crowded Web"
twitter                = "https://twitter.com/pajohannessen"
